# The host address to use when listening
host: 127.0.0.1
# The level of logging that should be used: INFO,WARN,ERROR,FATAL,DEBUG
log_level: INFO
# Settings for the redirector server
redirector_server: 
  # Port to listen for connections on
  port: 42127
# Settings for the redirect packet
redirector_packet: 
  addr: 0
  # Host to redirect to
  host: '383933-gosprapp396.ea.com'
  # The address to redirect to
  ip: 127.0.0.1
  # Port to redirect to
  port: 14219
  secu: 0
  xdns: 0